apiVersion: v1
kind: Service
metadata:
  name: {{ include "practica-ramon-keepcoding.fullname" . }}  # Usamos el nombre completo del release para evitar confusiones
  namespace: mi-practica-keepcoding
spec:
  selector:
    app: {{ include "practica-ramon-keepcoding.name" . }}  # Coincide con el selector del Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.miAppPractica.service.type }}  # Asegúrate de definir este valor en values.yaml
