apiVersion: v1
kind: Pod
metadata:
  name: stress
  namespace: mi-practica-keepcoding
spec:
  containers:
  - name: stress
    image: busybox
    command:
      - sleep
      - "3600"
  restartPolicy: Never
