apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordpress
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - mi-practica-keepcoding
  selector:
    matchLabels:
      App: wordpress
