apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "practica-ramon-keepcoding.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 "host" }}  # Usamos index para acceder al primer host
      http:
        paths:
          - path: {{ index (index .Values.ingress.hosts 0 "paths") 0 "path" }}  # Accedemos al primer path
            pathType: {{ index (index .Values.ingress.hosts 0 "paths") 0 "pathType" }}
            backend:
              service:
                name: {{ include "practica-ramon-keepcoding.fullname" . }}
                port:
                  number: 80
